Dockerfile
README.md
deploy/provider-gcp-plugin.yaml.tmpl
examples/app-secrets.yaml.tmpl
examples/mypod.yaml.tmpl
go.mod
main.go
scripts/build.sh
scripts/deploy.sh
scripts/example.sh

Adds a run-able binary that conforms to the [driver interface](https://github.com/kubernetes-sigs/secrets-store-csi-driver#criteria-for-supported-providers).
The deploy mechanism is similar to the azure and vault plugins (deploy a `DaemonSet` that copies the binary to a directory on the host), but I decided to do that in the go-code itself rather than as an entrypoint script.
A follow up PR will actually read from the Secret Manager API.

💥: initial running no-op plugin

---

config/config.go
config/config_test.go
examples/app-secrets.yaml.tmpl

Fixes #6 
The main driver only interprets the top level `parameters` dictionary. So long as all values in that dictionary are strings it should match the schema.

SecretProviderClass: remove nesting for secrets parameter

---

Dockerfile

distroless now recommends referencing debian 9 or debian 10 variants of their images: https://github.com/GoogleContainerTools/distroless#base-operating-system
Also we build as a static binary so we do not need everything included in the `base` variant: https://github.com/GoogleContainerTools/distroless/tree/master/base#documentation-for-gcriodistrolessbase-and-gcriodistrolessstatic
Cuts the image size from 60.4MiB to 44.9MiB.

Dockerfile: use smaller static image

---

README.md
deploy/provider-gcp-plugin.yaml
scripts/cloudbuild.yaml

Resolves #10. Builds & pushes must still be triggered manually.
Blocked on permissions to `*-docker.pkg.dev/secretmanager-csi` being expanded to `allUsers`.

build: provide a pre-built image

---

Makefile

Currently, misspell marks UK spellings as incorrect (e.g. "cancelled"). This reverts it to the default of allowing all valid english spellings.

Use neutral locale for misspell

---

test/infra/configs/config-management.yaml

SSH fails with
```
"Cloning into '/repo'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
" }
```
Since this is a public repo, we can just clone with HTTPS

Use https instead of SSH to clone repo for ACM

---

test/e2e/e2e-test-job.yaml.tmpl

This ensures that they're parsed as strings, even when they comprise of all numbers

Explicitly quote environment variables

---

README.md
auth/auth.go
config/config.go
config/config_test.go
test/e2e/README.md

If https://github.com/kubernetes-sigs/secrets-store-csi-driver passed along the `csi.storage.k8s.io/serviceAccount.name` attribute then we could eliminate the call to get the information about the pod for the mount event.
It also lets us remove the pod get permission.
https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1855-csi-driver-service-account-token/README.md would be even nicer as it would let us remove the `serviceaccounts/token` `create` permission, but that may take much longer to land. 
Blocked by https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/267

auth: remove GET Pod when SA is passed by driver

---

config/config.go

This would need to be set in the CSI driver DaemonSet NOT in the plugin DaemonSet to print information during actual mount events.
Fixes #4

DEBUG: introduce a DEBUG envvar to print extra information

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/iam-policy.yaml

In preparation for moving the `docker` commands in `test/e2e/build.sh` to Cloud Build. Currently, a build errors with 
```
AccessDeniedException: 403 735463103342@cloudbuild.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.
```
https://cloud.google.com/cloud-build/docs/cloud-build-service-account#default_permissions_of_service_account outlines the required permissions.

Grant cloud build service account permissions

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/iam-policy.yaml

Even with the current permissions, we're getting the error
```
service account "735463103342@cloudbuild.gserviceaccount.com" has insufficient permission to execute the build on project "secretmanager-csi-build"
```
This restores the "Cloud Build Service Account" role per https://cloud.google.com/iam/docs/understanding-roles#cloud-build-roles

Grant Cloud Build SA cloudbuild.builds.builder

---

test/infra/README.md
test/infra/anthos-managed/namespaces/secretmanager-csi-build/prow-pod-utils-sa.yaml
test/infra/anthos-managed/namespaces/test-pods/namespace.yaml

This service account will be used to store logs in the Prow instance

Add SA for Prow Pod Utils

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/integration-test-resources.yaml

Create a service account and a test secret in the build project for
use by integration tests. The SA will have permissions to read the
secret.
The secret value is 'hunter2' and is a test value only, it provides no
access to any external systems!
Create the static assets for https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/12 and the integration tests that will be needed for https://github.com/kubernetes-sigs/secrets-store-csi-driver#criteria-for-supported-providers

test infra: add resources to use with integration testing

---

deploy/provider-gcp-plugin.yaml
deploy/provider-gcp-plugin.yaml.tmpl

The plugin does not create the mount, just interacts with mounts created by the CSI driver. `HostToContainer` is sufficient and does not require `privileged: true`.
Note: the pod still has permissions to create a token as any service account, so while it directly isnt `privileged` it could _create tokens_ for `privileged` Pods.

priv: remove need for privileged container

---

server/server.go

Specifically don't want to use the node identity.
For integration tests to work in Kind, we likely will need to skip workload identity. For that we could support using `nodePublishSecretRef`

auth: fail if workload identity fails

---

config/config.go
config/config_test.go
server/server.go

Allows the pod definition to specify a K8S secret that the CSI driver should use when authenticating to GCP:
```
volumes:
- name: secrets-store-inline
csi:
driver: secrets-store.csi.k8s.io
readOnly: true
volumeAttributes:
secretProviderClass: "gcp-sync"
nodePublishSecretRef:
name: secrets-store-creds
```
The Secret should be an exported SA credential:
```
gcloud iam service-accounts keys create OUTPUT-FILE --iam-account=IAM_ACCOUNT
```
and loaded like:
```
kubectl create secret generic secrets-store-creds --from-file=key.json=PATH-TO-KEY-FILE.json
```
This will be used when creating kind integration tests that may not run in an environment where workload identity or GCE instance metadata is available.

auth: support nodePublishSecretRef

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml

Release built from:
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/commit/4722ffa0af341b799fcd26e3c8974da833d482a1

v0.1.0: update yaml to new image sha

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/iam-policy.yaml

The pod executed by Prow on our cluster needs permissions to build images (via Cloud Build) to run tests and GKE permissions to create pods

Grant prow service account presubmit IAM permissions

---

CHANGELOG.md
main.go

Observed some errors:
```
2020/10/21 23:51:40 Unable to listen to unix socket: listen unix /etc/kubernetes/secrets-store-csi-providers/gcp.sock: bind: address already in use
```

main: cleanup socket before attempting to listen

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml

v0.2.0 image built, release-0.2 branch is protected. After merged this will be tagged at with v0.2.0

v0.2.0: update yaml to new image sha and changelog

---

test/e2e/Dockerfile
test/e2e/mount_test.go
test/infra/prow/presubmit.sh

v0.0.18 includes necessary grpc flags, and installs to kube-system so we should test against that.
Also install the `rbac-secretprovidersyncing.yaml` bindings for future tests of the k8s syncing feature.

test: update e2e tests to use v0.0.18

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/prow-pod-utils-sa-iam-policy.yaml
test/infra/anthos-managed/namespaces/test-pods/prow-test-sa.yaml

after this is running a PR will be made to remove `GOOGLE_APPLICATION_CREDENTIALS` from 
https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/72

workload-id: bind test-pods/default to prow-pod-utils@

---

go.mod
go.sum
server/server.go
server/server_test.go

Addresses Issue #52 and and Issue #19.
Any non-retryable error will result in an INTERNAL error response to the`secrets-store-csi-driver`. Blocking pod scheduling is desirable to provide fast feedback on misconfigurations. This error concatenate all errors to speed up the test-fix cycle.
The rotation  scenario will keep trying rotations, but no filesystem changes will take effect until all secret accesses succeed. Rotation failures wont update data but will generate pod events.
The output of `kubectl describe pod <pod>` are of the form:
```
MountVolume.SetUp failed for volume "mysecret" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/mypod, err: rpc error: code = Internal desc = rpc error: code = …
```

partial errors: combine all access errors into a single error

---

CHANGELOG.md
docs/debugging.md
main.go

while performing some load tests https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/32 this was useful (specifically `debug/pprof/trace?seconds=5`) to find slowdowns. (I found that the k8s client has a default built in rate limiter).

pprof: add an option to enable pprof profiling

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml
deploy/provider-gcp-plugin.yaml.tmpl

Built and tagged images off of `release-0.3` at commit `c801110c2d51e8fc58e74d9ee2a0eafaeda79cd2`.
Updating changelog shas and `deploy/provider-gcp-plugin.yaml` with the new image and liveness probe configuration.
After this is merged into `release-0.3` branch, it will be tagged as v0.3.0 and then merged into `main`

v0.3.0: update yaml to new image sha and changelog

---

auth/auth.go

Make use of the provided context introduced [here](https://github.com/christopherL91/secrets-store-csi-driver-provider-gcp/blob/main/auth/auth.go#L57) using [http.NewRequestWithContext](https://golang.org/pkg/net/http/#NewRequestWithContext) available since version `1.13`

Use provided context for external calls

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml
docs/releasing.md

pull changes from `release-0.4` branch into `main`

v0.4.0: update deploy + changelog (#111)

---

test/e2e/e2e-test-job.yaml.tmpl
test/e2e/mount_test.go
test/e2e/templates/test-cluster.yaml.tmpl
test/e2e/templates/test-pod.yaml.tmpl
test/infra/prow/presubmit.sh

Allow testing against rapid/stable/regular update channels of gke.
These will be set in the oss-test-infra repo through envvars.
Also updates the default provider version for tests to v0.0.23

testing: parameterize the gke version

---

main.go
test/e2e/templates/provider-gcp-plugin.yaml.tmpl

Next step of https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/98 - default to returning files for the driver to write.
Requires driver v0.0.21 or greater (prefer v0.0.22+ for atomic file writing).
A future release will deprecate the flag, remove all file writing logic from the gcp plugin, and remove the host paths.

flags: default write_secrets to false

---

CHANGELOG.md
README.md

- update the unreleased portion of the changelog
- all gke supported versions will work (removing the 1.16+ note)
- give a brief summary of auth before the steps to configure auth

docs: update readme to clarify auth

---

CHANGELOG.md
main.go
server/server.go
server/server_test.go

Remove the `-write_secrets` entirely from the next release.
Integration tests have been running with the flag and `test/e2e/templates/provider-gcp-plugin.yaml.tmpl` has been running with the mount removed from pod.
Removing the mount will be done separately so that users who kubectl apply `deploy/provider-gcp-plugin.yaml` won't get a half-released yaml.
Resolves most of #98 excluding the `yaml` update which will be done in #124

write_secrets: remove option to write secrets directly

---

deploy/provider-gcp-plugin.yaml

Starting in 0.6.0 only write secrets through the grpc interface
Closes out https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/98

write_secrets: remove host volume mount

---

CHANGELOG.md
go.mod
main.go
server/server.go
server/server_test.go

Addresses #94
Creates the SM client once in `main` backed by a pool of  (currently) 5 underlying connection. On `Mount` requests then add Per RPC auth with the correct tokensource.

feat: re-use secretmanager client

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/integration-test-resources.yaml

Declare a GCP secret to hold an exported SA credential for the:
`k8s-csi-test@secretmanager-csi-build.iam.gserviceaccount.com`  identity
This is then sync'd to the https://github.com/kubernetes/test-infra prow instance as `gcp-secrets-store-cred` K8s secret and injected into the https://github.com/kubernetes-sigs/secrets-store-csi-driver integration tests as [`GCP_SA_JSON`](https://github.com/kubernetes/test-infra/blob/2e9846ac845543cdb68a5f3b3faca52653597e3d/config/jobs/kubernetes-sigs/secrets-store-csi-driver/secrets-store-csi-driver-presets.yaml#L30-L37).
Once available there, it is [passed to this provider](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/7cef422aeae158f3cd8ccb6f1be3e60ba82cdcd4/test/bats/tests/gcp/pod-secrets-store-inline-volume-crd.yaml#L19-L26) as a …

tests: configure secret and ACLs for k8s prow syncing

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/integration-test-resources.yaml

Allow the oss k8s prow jobs to act as:
k8s-csi-test@secretmanager-csi-build.iam.gserviceaccount.com
using workload identity.
This would replace https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/129 and remove the need to export a service account credential for the integration tests.

iam: allow k8s prow to act as k8s-csi-test with WI

---

auth/auth.go
main.go
server/server.go

Build all clients in main and inject into handlers. Declaring the dependencies up front allow them to establish connections before servicing requests.
Completes https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/94

chore: move all external client initializaitions to main.go

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/integration-test-resources.yaml

The driver project now uses workload identity to act as the k8s-csi-test
service account in prow job/integration tests.
This removes the need to export a k8s-csi-test service account credential
and write to secret manager and sync that secret to prow.
Block on https://github.com/kubernetes-sigs/secrets-store-csi-driver being [fixed](https://testgrid.k8s.io/sig-auth-secrets-store-csi-driver-presubmit#pr-secrets-store-csi-driver-e2e-gcp)

test: remove sync secret for prow jobs

---

.github/workflows/e2e.yml

The:
```
environment:
name: e2e-test
```
requires manual approvals to gate access to the `GCP_CREDENTIALS` secret.
It may be OK to remove the action environment protection with the following settings:
But need verification first. Also unclear whether 'environment' is even something that can be filtered on when setting up federated auth: https://github.com/google-github-actions/auth#setup
EDIT:  On further inspection, actions triggered from a fork PR [will never get access to secrets](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) so I think this means that we just cant run the e2e tests on outside contributions automatically (or prior to submission).

tests: scheduled e2e test

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml

Bring 1.0 changes into `main`, step 7 of https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/docs/releasing.md

v1.0.0: update deploy + changelog (#153)

---

.github/workflows/e2e.yml

Address warning:
```
Warning: google-github-actions/setup-gcloud is pinned at HEAD. We strongly advise against pinning to "@master" as it may be unstable. Please update your GitHub Action YAML from:
uses: 'google-github-actions/setup-gcloud@master'
to:
uses: 'google-github-actions/setup-gcloud@v0'
Alternatively, you can pin to any git tag or git SHA in the repository.
```

chore: pin to v0 instead of master for gcloud action

---

config/config.go
infra/grpc.go

Default:
- no request/response logs
level 2:
- log responses
level 3:
- log requests
- log auth information
`-v=2`:
```
{"ts":1643759283107.3394,"caller":"secrets-store-csi-driver-provider-gcp/main.go:78","msg":"starting secrets-store-csi-driver-provider-gcp/273e260","v":0}
{"ts":1643759283109.2644,"caller":"secrets-store-csi-driver-provider-gcp/main.go:218","msg":"health server listening","v":0,"addr":":8095"}
{"ts":1643759329506.261,"caller":"infra/grpc.go:40","msg":"response","v":2,"method":"/v1alpha1.CSIDriverProvider/Mount","deadline":"1m59.997721304s","duration":"286.160302ms","status.code":"OK","status.message":""}
```
`-v3`:
```
{"ts":1643759462909.7842,"caller":"secrets-store-csi-driver-provider-gcp/main.go:78","msg":"starting secrets-store-csi-driver-provider-gcp/273e260","v":0} …
```

logging: add explicit log levels for debug info

---

.github/workflows/e2e.yml
test/e2e/Dockerfile
test/infra/runner.sh

Clears the github action warning:
```
"service_account_key" has been deprecated. Please switch to using google-github-actions/auth which supports both Workload Identity Federation and Service Account Key JSON authentication. For more details, see https://github.com/google-github-actions/setup-gcloud#authorization
```
and clears the gke / kubectl / gcloud warning:
```
CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable. Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```
The instructions on https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke were actually wrong, they …

chore: update tests to clear warnings

---

config/config.go
config/config_test.go
server/server.go
server/server_test.go
test/e2e/mount_test.go
test/e2e/templates/test-mode.yaml.tmpl

Allow user to define file permissions per secret with `mode` configuration option. Mode can be defined as octal or decimal value, e.g., `0400` or `256`.  If `mode` is not set for a secret continue to use `MountRequest.GetPermission()` as a default.
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
name: gcp-test-secrets
spec:
provider: gcp
parameters:
secrets: |
- resourceName: "projects/my-project/secrets/my-secret/versions/latest"
path: "my-private-key.pem"
mode: 0400
```
Related issue: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/722
Precedent for `mode` as `*int32`: https://github.com/kubernetes/api/blob/79091dac6a32a1365edbc6de9576ffa74768a75c/core/v1/types.go#L1194

feat: add configuration for per secret file permission

---

README.md
charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/templates/_helpers.tpl
charts/secrets-store-csi-driver-provider-gcp/templates/clusterrole.yaml
charts/secrets-store-csi-driver-provider-gcp/templates/clusterrolebinding.yaml
charts/secrets-store-csi-driver-provider-gcp/templates/daemonset.yaml
charts/secrets-store-csi-driver-provider-gcp/templates/serviceaccount.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml

Add helm charts for `provider-gcp-plugin`.
When we want to add some properties to the manifest (`deploy/provider-gcp-plugin.yaml`), we needed to either way of the followings.
1. Copy the manifest file to our own repository and edit it.
2. `kubectl patch` after `kubectl apply deploy/provider-gcp-plugin.yaml`.
If we choose 1., we have to update the copied manifest, when the original in this repository updates. In the case of 2., we need some shell scripts to deploy. 
This PR makes it easy to deploy this plugin with some changes (like `taints` or `nodeSelector`).  
If this change seems acceptable, I will add some tests.
This is my first contribution to this repository, therefore I would really appreciate any feedback, suggestions and change requests.

Add helm charts to make it easier to change some values

---

scripts/cloudbuild-dev.yaml
scripts/cloudbuild-release.yaml

Fix the cloud build script from https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/193.
building arm64 requires extending the timeout and apparently the cloud build format for docker buildx pushes is different so adding the `--push` flag instead of using the `images` output in the yaml

fix: extend timeout and docker buildx push syntax

---

CHANGELOG.md
charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml
deploy/provider-gcp-plugin.yaml

Prep for v1.2.0 release,
See full list of changes at:
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/compare/v1.1.0...d2834985815be4c62762ea281cc20a35ca9d428d

v1.2.0: update deploy + changelog + helm

---

CHANGELOG.md
charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml
deploy/provider-gcp-plugin.yaml

Bring v.1.2.0 updates to `main`. https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/releases/tag/v1.2.0
Last step on https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/docs/releasing.md#releasing

v1.2.0: update deploy + changelog + helm (#221)

---

deploy/provider-gcp-plugin.yaml

Since https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/193 the image is built to support amd64 and arm64
If you want to use arm64 nodes today (e.g., T2A nodes on GKE) you have to apply a [patch](https://github.com/wolfi-dev/wolfictl/blob/d1d33c7c57bf9e4d3e4090e824d43b7635dcb2d7/scripts/arm-patch.yaml) to make the GCP secrets-store provider work, which isn't well documented or discoverable, and will only trip people up.
This change makes the provider DaemonSet tolerate arm64 nodes by default, if they happen to be present.

Have DaemonSet tolerate arm64 nodes

---

deploy/provider-gcp-plugin.yaml
test/e2e/templates/provider-gcp-plugin-wif.yaml.tmpl
test/e2e/templates/provider-gcp-plugin.yaml.tmpl

Set the DaemonSet flags to prevent the sharing of the Host UTS and Host Network namespaces

Prevent the sharing of any host namespaces

---

charts/secrets-store-csi-driver-provider-gcp/templates/daemonset.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml

This PR exposes the `priorityClassName` variable to the helm chart, allowing it to be set on the daemonset.
Related to: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/204
There should be no impact on existing deployments where this variable is not set.

Expose `priorityClassName` variable to the helm chart

---

deploy/provider-gcp-plugin.yaml

For all volumeMounts defined in the GCP Provider plugin, set the value of parameter mountPropogation to None.

Set mount propagation mode to None.

---

README.md
charts/secrets-store-csi-driver-provider-gcp/templates/apparmor-profile.yaml.tmpl
charts/secrets-store-csi-driver-provider-gcp/templates/daemonset.yaml
deploy/apparmor-profile.yaml.tmpl
deploy/provider-gcp-plugin.yaml
scripts/deploy.sh
test/e2e/templates/apparmor-profile.yaml.tmpl
test/e2e/templates/provider-gcp-plugin-wif.yaml.tmpl
test/e2e/templates/provider-gcp-plugin.yaml.tmpl

Resolving the security vulnerability of verifying the AppArmor Profile to manage access permissions and network communication restrictions for the provider's container.
The AppArmor profile has been authored from the AppArmor profile Go code specified at [Kubernetes's Profile Reference](https://kubernetes.io/docs/tutorials/security/apparmor/#authoring-profiles) in the runtime/default section. The corresponding [AppArmor Profile Github Link](https://github.com/containers/common/blob/main/pkg/apparmor/apparmor_linux_template.go) is in Go and the AppArmor defined in the PR is in YAML to enable binding of the AppArmor Profile to the DaemonSet as ConfigMap.
The AppArmor Profile cannot be set as a YAML key-value pair as defined in the [API …

Add AppArmor security profile to manage access and network communication.

---

auth/auth.go
csrmetrics/csrmetrics.go
csrmetrics/csrmetrics_test.go
go.mod
go.sum
server/server.go

Exported metrics are as below:
Request Count and Latency of all the calls to the GCP IAM and GCP Secret Manager.
Example metrics view on `localhost:8095/metrics`
```
outbound_rpc_count{kind="gcp_iam_get_id_bind_token_requests",status="200"} 6
outbound_rpc_count{kind="secretmanager_access_secret_version_requests",status="PermissionDenied"} 4
outbound_rpc_count{kind="secretmanager_access_secret_version_requests",status="ok"} 8
outbound_rpc_latency_bucket{kind="gcp_iam_get_id_bind_token_requests",status="200",le="0.005"} 0
outbound_rpc_latency_bucket{kind="gcp_iam_get_id_bind_token_requests",status="200",le="0.01"} 0
outbound_rpc_latency_bucket{kind="gcp_iam_get_id_bind_token_requests",status="200",le="0.025"} 4
outbound_rpc_latency_bucket{kind="gcp_iam_get_id_bind_token_requests",status="200 …
```

Configure and Export Prometheus metrics

---

auth/auth.go
docs/fleet-wif-notes.md

Presently the provider is limited to only work with GKE or Fleet Workload Identity pool providers. This PR ensures that the gcp provider may retrieve secrets on a cluster utilizing [GOOGLE_APPLICATION_CREDENTIALS](https://cloud.google.com/docs/authentication/application-default-credentials#GAC) pointing to an audience pool provider backed by [Workload Identity Federation with Kubernetes](https://cloud.google.com/iam/docs/workload-identity-federation-with-kubernetes).
Fixes: #206

feat: enable Workload Identity Federation with Kubernetes and add docs

---

test/infra/managed/namespaces/secretmanager-csi-build/iam-policy.yaml

1. Added relevant parameter manager admin permissions to e2e service account as getting permission denied errors in e2e tests 
```
TEST: + /google-cloud-sdk/bin/gcloud secrets delete testsecret-1376340465-extract --project secretmanager-csi-build --quiet
TEST: ERROR: (gcloud.secrets.delete) NOT_FOUND: Secret [projects/735463103342/secrets/testsecret-1376340465-extract] not found. This command is authenticated as e2e-test-sa@secretmanager-csi-build.iam.gserviceaccount.com which is the active account specified by the [core/account] property.
TEST: 
TEST: + /google-cloud-sdk/bin/gcloud parametermanager parameters versions delete testparameterversionyaml-1030579760 --parameter testparameteryaml-841516529 --location global --project secretmanager-csi-build --quiet
TEST: ERROR: …
```

Added relevant parameter manager admin roles

---

charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml

Failed job 
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/actions/runs/14396802787/job/40373862575?pr=542

Correct the helm charts as the job failed when we released 1.8

---

charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml

Due to direct commit on main e6c6bf3b56a2d0ff1a21a4057ebe26ee07e9f28f, release workflow did not trigger. Hence manually updating the main charts.

[1.9.0] Upadte the helm charts

---

README.md
docs/authentication.md
examples/mypod.yaml.tmpl

Customers should use Workload Identity Federation using direct principal binding. This method avoids the intermediate impersonation step.

Update Readme with Workload Identity Federation
