GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp

README.md

Add a support disclaimer per https://opensource.google/docs/releasing/publishing/#disclaimer

readme: add support disclaimer

---

README.md

Add a section with security considerations and the recommendation that directly calling the API is the most secure.

Security Considerations

---

main.go
server/server.go

After submitting #51 I noticed the path joining package was incorrect and wanted to test out grpc deadline propagation.
Addresses #47

grpc: miscellaneous fixes

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/iam-policy.yaml

This is needed to actuate changes from #54

grant roles/secretmanager.admin

---

README.md

Add a hyperlink in README for example

---

README.md
docs/testing-notes.md

Now that v0.0.17 is released update install notes

docs: update for 0.2.0 release

---

test/infra/anthos-managed/namespaces/secretmanager-csi-build/prow-pod-utils-sa-iam-policy.yaml

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/72

workloadid: fix prow-pod-utils IAM SA reference

---

CHANGELOG.md
config/config.go
main.go

Document changes that will be released in v0.3.0

Docs: prep for v0.3.0

---

config/config.go
infra/grpc.go
main.go

- correct typos
- Infof -> InfoS was not properly formatting some fields
- Log deadline and duration in grpc middleware
- rename status code and message to not conflict with "msg" field

logs: various log improvements

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml
deploy/provider-gcp-plugin.yaml.tmpl

bring v0.3.0 changes into main

v0.3.0: update yaml to new image sha and changelog (#90)

---

.github/workflows/test.yml
Dockerfile
go.mod
test/e2e/Dockerfile
test/e2e/go.mod
test/e2e/mount_test.go
test/e2e/templates/test-cluster.yaml.tmpl
test/e2e/test-secret-mounter/go.mod

attempt to fix issues from https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/102#issuecomment-834714234

testing: update to 1.16 and increase timeout

---

main.go

This PR fixes issue #93, minimum go version is now 1.16 as it's introduces the call to [signal.NotifyContext](https://golang.org/pkg/os/signal/#NotifyContext)

Use notifycontext. fixes #93

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml
docs/releasing.md

Prep release-0.4 branch for v0.4.0 release

v0.4.0: update deploy + changelog

---

CHANGELOG.md
auth/auth.go
config/config.go
config/config_test.go
docs/authentication.md
server/server.go

Address https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/101

feat: auth options

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml

Prep release-0.5 branch for v0.5.0 release

v0.5.0: update deploy + changelog

---

CHANGELOG.md
deploy/provider-gcp-plugin.yaml

Bring release-0.5 changes into the `main` branch

v0.5.0: update deploy + changelog (#121)

---

docs/testing-notes.md
scripts/load-test.sh
test/e2e/templates/load-many-secrets.yaml.tmpl
test/e2e/templates/load-one-secret.yaml.tmpl

Addresses https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/32

tests: add a load test

---

test/e2e/Dockerfile
test/e2e/enable-rotation.sh
test/e2e/mount_test.go
test/e2e/templates/test-rotate.yaml.tmpl

Add an integration test for secret rotation

test: rotation

---

test/e2e/mount_test.go
test/e2e/templates/test-sync.yaml.tmpl

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/37

test: e2e test for secret syncing to k8s secrets

---

README.md

Adds link/image to tests added from #103

docs: add link to testgrid for periodic tests

---

test/infra/runner.sh

The e2e tests fail every morning and then work when retried. For some reason gke seems to not respond well and the tests fail waiting on the pod, saying the pod doesnt exist.
First poll for the pod to exist and then use kubectl wait.

fix: poll for e2e test pod to exist

---

Dockerfile
deploy/provider-gcp-plugin.yaml
scripts/cloudbuild-dev.yaml
scripts/cloudbuild-release.yaml

https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/191
Signed-off-by: Jason Hall <jason@chainguard.dev>

Build multi-platform image for arm64

---

scripts/cloudbuild-dev.yaml
scripts/cloudbuild-release.yaml

Signed-off-by: Jason Hall <jason@chainguard.dev>
#191

fix multiarch build by creating buildx context

---

CHANGELOG.md
charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml
deploy/provider-gcp-plugin.yaml

Changes in: helm, deploy, CHANGELOG.md

SHA changes for 1.3.0 release

---

CHANGELOG.md
charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml
deploy/provider-gcp-plugin.yaml

* v1.3.0: Deploy + CHANGELOG.md changes
* Added arm64 DaemonSet and Workload Identity changes to CHANGELOG.md

v1.3.0: SHA changes for 1.3.0 release (#299)

---

.github/workflows/e2e.yml
test/infra/managed/namespaces/secretmanager-csi-build/iam-policy.yaml

Update deadline 45 -> 60 minutes

Update deadline of e2e tests

---

deploy/provider-gcp-plugin.yaml

Use the recommended container configuration.

Use secure container config

---

CODEOWNERS
auth/auth.go
deploy/provider-gcp-plugin.yaml
vars/vars.go

Reads: SM_PROVIDER_ID_BINDING_TOKEN_ENDPOINT and SM_PROVIDER_GKE_WORKLOAD_IDENTITY_ENDPOINT

Read Endpoints from Environmental Variables

---

CHANGELOG.md
charts/secrets-store-csi-driver-provider-gcp/values.yaml
deploy/provider-gcp-plugin.yaml

Update SHA keys in deploy and changelog for 1.5.0 release

v1.5.0 update deploy + changelog (#378)

---

CHANGELOG.md
charts/secrets-store-csi-driver-provider-gcp/values.yaml
deploy/provider-gcp-plugin.yaml

Update SHA keys in deploy and changelog for 1.5.0 release

Update Main with release 1.5

---

charts/secrets-store-csi-driver-provider-gcp/templates/daemonset.yaml
test/e2e/templates/provider-gcp-plugin-wif.yaml.tmpl
test/e2e/templates/provider-gcp-plugin.yaml.tmpl

Add missing changes from https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/370

Add rootless changes to template files

---

CHANGELOG.md
charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/values.yaml
deploy/provider-gcp-plugin.yaml

Changes in: helm, deploy, CHANGELOG.md

SHA changes for 1.6.0 release

---

test/infra/managed/namespaces/secretmanager-csi-build/iam-policy.yaml

Added arpangoswami as a human admin as I was getting 403 errors for this command, I'm currently an engineer working on this project at Google

Added arpangoswami as a human admin

---

test/e2e/mount_test.go
test/infra/runner.sh

Added better log visibility for e2e parallel tests

Added better log visibility

---

README.md
examples/app-parameters.yaml.tmpl
scripts/pm_example.sh

* Added instructions to mount parameter version (rendered) 
* Added script to mount the parameter versions with the help of template files.

Add example and README for Parameter Manager support

---

config/config.go

Change log level for nodepublish ref message
